### ISSUE TITLE
No TB3 with latest tb3 firmware provided by ASRock TSD

### ISSUE THREAD

**Issue by deliad2** [iGPU/AMD_OC_Ryzen#13]
want to tell that ive received TB3 Firmware for the X570 Creator from ASRock TSD

I flashed it and now my RME Fireface UFX Plus TB2 interface (with apple tb2 to tb3 adapter) not recongnized in with @iGPU OC Folder

attached here the link for tb3 flash image for you to test, it improves stability on windows

windows driver
http://download.asrock.com/TSD/Desktop/Driver/thunderbolt%28tm%2917.4.80.550_19h1.zip

windows flashable firmware
https://drive.google.com/open?id=1Yql0A0-jDaQAFgS1QFJh3r2Nsy3xSeYA

have a try maybe with that firmware we can solve the tb3 issues completely

**Comment by iGPU** [comment]
It won't matter with macOS. To get TB3 working with macOS, we need to flash firmware to the TB chip. Once this is done, the TB will not work under Windows. At this point, you get one or the other (macOS or Windows). But even then, I was not successful in flashing this mobo. I have since moved on and don't use this mobo.

**Comment by peterjohnjoseph** [comment]
> It won't matter with macOS. To get TB3 working with macOS, we need to flash firmware to the TB chip. Once this is done, the TB will not work under Windows. At this point, you get one or the other (macOS or Windows). But even then, I was not successful in flashing this mobo. I have since moved on and don't use this mobo.

Out of curiosity, have you switched to another motherboard?
