### ISSUE TITLE
10.15.3 -> 10.15.4 fails

### ISSUE THREAD

**Issue by ne4u** [iGPU/AMD_OC_Ryzen#2]
Including this kernel patch will fix the issue:
https://github.com/AMD-OSX/AMD_Vanilla/commit/0f4c0139eeaf0c598287ee4f5f9c4a947064d8bb

**Comment by iGPU** [comment]
Thanks for update; I'm mostly using Mojave and Catalina has been 10.15.4beta which didn't have that issue.

**Comment by pieter91** [comment]
I'm running 10.15.4 successfully. Only problems I've got are USB related. Stuttering in USB audio, the cursor juttering and failure to shut down or sleep properly.

**Comment by gurkerl83** [comment]
Here too, failure to shut down or sleep does not work. The first was working in a earlier version, sleep never works.

**Comment by iGPU** [comment]
Sleep is not just an AMD Hackintosh issue but affects most builds. No easy fix. See some comments on this thread/post: https://www.tonymacx86.com/threads/success-gigabyte-designare-z390-thunderbolt-3-i7-9700k-amd-rx-580.267551/post-2094199

Occasionally, shut down issues are due to corrupted BIOS. First try doing a full shutdown with AC cord unplugged, then press the on button a few times. Only then reconnect AC cord and boot. After booting do a shutdown and see if it's fixed. Only then consider re-flashing BIOS and re-storing previous settings.

As for stuttering Audio, this too is not uncommon on Hackintoshes. Some searches should help give you ideas, such as trying different ALC codes, like 1, 2, 5, 7, 11. One common issue is whether the problem is only on the front port or on the Audio port coming directly off the mobo. Sometimes only one or the other works well.
