### ISSUE TITLE
SSDT-EC.aml - boot issue

### ISSUE THREAD

**Issue by ne4u** [iGPU/AMD_OC_Ryzen#4]
With SSDT-EC.aml enabled the system fails to boot.

No Local Variables are initialized for method [_PRW]
No Arguments are initialized for method [_PRW]
ACPI Error: Method parse/execution failed [\_SB.USBW._PRW]

Disabling allows the system to boot.

**Comment by iGPU** [comment]
Yes, I noticed issues with _PRW this week. I didn't see a boot problem but could not attach _PRW to any devices on the X570 mobo. Therefore, I removed this from SSDT-EC and updated a few days ago. I'd also recommend disabling USBWakeFixup since this depended on _PRW to work. I'll work on it perhaps next week as time is consumed by TB issues.
