### ISSUE TITLE
OCB: No Protocols for Schema at 6 Index

### ISSUE THREAD

**Issue by itaki** [iGPU/AMD_OC_Ryzen#8]
x570 Creator, 3950x. Using the EFI straight out of the box, right after the bios loads "OCB: No Protocols for Schema at 6 Index" error pops up and it goes straight to bios.

**Comment by vade** [comment]
Did you install your EFI folder into the root of your EFI partition, or did you install your OC / BOOT folders into the root of your EFI partition?

You should have <EFI parition>/EFI/OC and BOOT

Are you belt to boot to the installer?

**Comment by itaki** [comment]
Definitely have an EFI folder on my EFI partition. 

Trying to boot to an installer.

**Comment by vade** [comment]
So amusingly I was messing with my config.plist and hit the same error when messing with the nvram boot `csr-active-config: E7030000 ` which is suggested in this repo. Removing it seemed to help.

**Comment by itaki** [comment]
Excellent! Thanks, I'll give that a shot.

**Comment by iGPU** [comment]
When bootloader returns to BIOS, it's almost always a structural error on user's part. If you carefully read the READ.MD it explains this. It also tells you were to look to trouble shoot: https://dortania.github.io/OpenCore-Desktop-Guide/troubleshooting/troubleshooting.html#booting-opencore-reboots-to-bios

Further, when updating, if you 'cherry pick' parts of a new build, you are almost always guaranteed to have a boot failure. Each part is critical especially since OpenCore often introduces new structural changes. It is strongly recommended on updating OC to study the Docs folder, reading the Differences page to see where changes were made, comparing these areas to your current config.plist file. (The config.plist file supplied already has had these changes applied.)

**Comment by itaki** [comment]
Yes, ok. Thank you @iGPU. I see I had at least 2 separate problems. The first being that I used the Auto+TB-CSM-BT.bin bios settings from the repository. When loading these bios settings, it did not affect 4G decoding, which I had turned off and npci=0x2000 was being used with a different EFI I was working with. Wonder why user settings don't affect boot settings. Guess user bios settings is just for all the advance stuff and overclocking and whatnot.

However, in trying to track down what that problem was, I swapped out opencore with the debug release. However on the [releases page](url=https://github.com/acidanthera/OpenCorePkg/releases) it lists 0.5.7 as the latest release, so that's what I used. 

Reading through your documentation it clearly indicates you are using v058, so my assumption was bad and that's what was causing the "No Protocols" error. 

Having said that though, where can one find the debug release of v058? I see [opencore-factory](https://github.com/williambj1/OpenCore-Factory/releases) does a nightly build. Or is there a stable release that I can snag from somewhere?

Thanks again for your help.
