### ISSUE TITLE
shikigva=80 needed?

### ISSUE THREAD

**Issue by vade** [iGPU/AMD_OC_Ryzen#9]
For Ryzen systems, does It make sense to add `shikigva=80` to the boot-args?

The [Whatevergreen chart](https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.Chart.md) indicates that for a iMac Pro model which is default in the config no `shikigva` or `shikigva=128` should be specified?

I am new to all of this, but disabling `shikigva=80` appears to have removed issues with 2 30 bit displays on a Radeon VII

If im missing some nuance, apologies!

**Comment by ne4u** [comment]
The maintainer may not be running 10.15.  Reading through the WEG comments, this might explain why 80 is the maintainer's default.  BTW 80 is not the ideal patch for my system either.

Looking at the 10.15 chart WEG chart it seems to indicate that no patch means software decoding will be used vs 128 which will use hardware decoding.  I'm guessing 128 might provide more performance w/ a Radeon VII.

ShikiGVA Patches for 80:

16 = Use hardware DRM decoder (normally AMD) by pretending to be iMacPro in apps that require it.
64 = Attempt to support fps.2_1 (FairPlay 2.x) in Safari with hardware decoder. Works on most modern AMD GPUs. Note, AMD Polaris Ellesmere is broken in 10.15 (e.g. RX 590), whereas AMD Polaris Baffin (e.g. RX 460) is fine.

**Comment by iGPU** [comment]
1) I use Mojave; I think Catalina is unstable: each update breaks/changes things
2) I made this EFI somewhat generic. You need to study the whole EFI and change it has you see fit. Thinking is encouraged. Trial and error are how I arrived at what is here; many hours.
3) If you read widely, you'll find sometimes 16, 32, 80, 128 or 256 is recommended. Over time, these values have changed as WEG has been updated. It also depends on what SMBIOS you use. Since the recommended one is iMacPro1,1, look at the WEG table and decide what functions are best served for you: https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.Chart.md  I use no entry; another contributor wanted this entry.

**Comment by vade** [comment]
Thanks for the explanation!
